#!/bin/bash

if [ -e ../lexer ]; then

  cat primes.min | ../lexer mytest.min > mytest.output
  diff mytest.output mytest.tokens > diff.output
  cat diff.output

  diffoutput=`cat diff.output`
  if [[ "$diffoutput" == "" ]]; then
    echo "PASSED"

  else
    echo "FAILED"

  fi

  rm mytest.output diff.output

else
  echo "Must compile lexer before running tests"

fi
